name: Idea or suggestion
description: Ideas and suggestions from the DataCite community about product features, metadata schema, and more.
labels: idea
title: "[IDEA] <Your idea title>"

body:
  - type: markdown
    attributes:
      value: |
      "## Describe your idea
      _These fields are required._"
  - type: textarea
    id: problem-description
    attributes:
      label: What is the problem that your idea solves?
      placeholder: Describe the problem that inspired your idea...
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: What solution would might meet your needs?
      placeholder: Describe the solution that you are imagining...
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Extra information
      _These fields are not required and help us understand more about your idea._"
  - type: textarea
    id: alternatives-description
    attributes:
      label: What alternatives have you tried or considered?
      placeholder: Describe alternative solutions, features, or workarounds...
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Is there anything else you'd like to share?
      placeholder: Additional context or screenshots about your idea...
    validations:
      required: false
  - type: checkboxes
    id: stakeholder-group
    attributes:
      label: What group(s) do you represent? 
      description: You may select more than one.
      options:
        - label: DataCite Member
        - label: Integrator or Service Provider
        - label: Metadata harvester
        - label: Researcher
        - label: Funder
        - label: Other
  - type: input
    id: other
    attributes:
      label: If other, please describe.
        
