name: Idea or suggestion
description: Ideas and suggestions from the DataCite community about product features, metadata schema, and more.
labels: idea
title: ""

body:
  - type: textarea
    id: problem_description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when ...
      placeholder: Describe the problem...
    validations:
      required: true
  - type: textarea
    id: solution_description
    attributes:
      label: What solution would might meet your needs?
      description: A clear and concise description of what you want to happen.
      placeholder: Describe the solution...
    validations:
      required: true
  - type: textarea
    id: alternatives_description
    attributes:
      label: What alernatives have you tried or considered?
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Describe alternatives...
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Is there anything else you'd like to share?
      description: Add any other context or screenshots about the feature request.
      placeholder: Additional context...
    validations:
      required: false
