name: Move new issues to triage
on:
  issues:
    types:
      - opened
jobs:
  transfer_issue:
    if: ${{ ! contains(github.event.issue.labels.*.name, vars.KEEP_LABEL ) }}
    needs: update-discussion
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue transfer "$ISSUE" datacite/product-suggestions-triage
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPO: ${{ github.repository }}
          ISSUE: ${{ github.event.issue.html_url }}
