name: Update labels
on:
  label:
    types: edited
jobs:
  update_labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: |
          response=$(gh label edit "$NAME" -n "$NEW_NAME" -c $NEW_COLOR -d "$NEW_DESCRIPTION" -R $DEST_REPO 2>&1)
          exit_code=$?

          if [[ "$response" == *"404"* ]] || [[ $exit_code != 1 ]]; then
            exit 0
          else
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NAME: ${{ github.event.changes.name.from && github.event.changes.name.from || github.event.label.name }}
          NEW_NAME: "${{ github.event.label.name }}"
          NEW_COLOR: "${{ github.event.label.color }}"
          NEW_DESCRIPTION: "${{ github.event.label.description }}"
          DEST_REPO: ${{ vars.DEST_REPO }}
