name: Update labels
on:
  label:
    types: [edited, deleted]
jobs:
  update-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install requests

      - name: Manage other labels
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPO: ${{ github.repository }}
          FROM_NAME: ${{ github.event.changes.name.from }}
          NAME: ${{ github.event.label.name }}
          NEW_NAME: "${{ github.event.label.name }}"
          NEW_COLOR: "${{ github.event.label.color }}"
          NEW_DESCRIPTION: "${{ github.event.label.description }}"
          DEST_REPO: ${{ vars.DEST_REPO }}
          EVENT_TYPE: ${{ github.event.action }}
        run: python .github/scripts/manage_label.py
